apiVersion: v1
kind: Secret
metadata:
  name: login-secret
  annotations:
    build.shipwright.io/referenced.secret: "true"
type: kubernetes.io/basic-auth
stringData:
  username: abhiramvarma92@gmail.com
  password: Varmas@20